# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "xinyao1994"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "DB": 
        filters: ["KV", "Index", "SSD", "NVMe", "Compression", "Datebase", "Cache"]
    "Network": 
        filters: ["RDMA", "Replication", "Training", "Inference", "DPU", "SmartNIC", "Programmable Switch", "Collective communication", "RPC", "CRDT", "MPI", "UCX", "NCCL"]
    "Artificial Intelligence": 
        filters: ["GPT", "Image Matching", "CV", "NeRF"]
    "Distributed, Parallel, and Cluster Computing": 
        filters: ["distributed system"]
    "Compiler": 
        filters: ["compiler"]
    "Data Structures and Algorithms":
        filters: ["algorithms"]
    "Hardware Architecture":
        filters: ["hardware"]
    "Information Retrieval":
        filters: ["information"]
    "Networking and Internet Architecture":
        filters: ["networking"]
    "Operating Systems":
        filters: ["system"]
    "Mixed Precision":
        filters: ["mixed precision"]
